import type { Metadata } from "next";

// The privacy policy the App Store listing and the Subscribe screen link to.
// A DRAFT in plain language, written from what the app actually does — read
// it through and adjust before submission; the two bracketed spots need your
// own details.

export const metadata: Metadata = {
  title: "Privacy — Tekan Buddy",
  description: "What Tekan Buddy stores, why, and how to get it removed.",
};

export default function PrivacyPage() {
  return (
    <main className="legal">
      <h1>Privacy Policy</h1>
      <p className="legal-date">Last updated: [date]</p>

      <h2>What Tekan Buddy is</h2>
      <p>
        Tekan Buddy is a running app with a voice trainer. You can use it without an
        account. Signing in adds run history, friends and the personal touches in the
        coaching.
      </p>

      <h2>What we store, and why</h2>
      <ul>
        <li>
          <strong>Your account.</strong> When you sign in with Google or Apple we keep your
          name, email address and profile picture so the app can recognise you. Your
          provider&apos;s account id is stored only as a one-way hash.
        </li>
        <li>
          <strong>Your runs.</strong> Distance, time, pace, splits and the GPS route of each
          run you save, plus where the run happened (city and neighbourhood) for the trainer
          to mention. Runs are visible only to you and to friends you have added who have
          added you back.
        </li>
        <li>
          <strong>Your stats.</strong> Age, height, weight, gender and home city, if you enter
          them on the Account screen. The trainer uses them in what it says to you; nothing
          else does.
        </li>
        <li>
          <strong>Apple Health.</strong> With your permission the app reads workouts and
          heart rate from Health to show them next to a run, and lets you adopt the
          Watch&apos;s distance. Health data is read on the phone and is not stored on our
          servers unless you choose to conform a run to it (then only the distance).
        </li>
        <li>
          <strong>Spotify.</strong> If you connect Spotify, we store its access tokens,
          encrypted, so the app can start your playlist and tell the trainer what is
          playing.
        </li>
        <li>
          <strong>Friends and cheers.</strong> Who you have added, comments on runs, and
          voice or text messages you send to a friend&apos;s run, until they have played.
        </li>
        <li>
          <strong>Subscription.</strong> Whether your account is on the free or full plan.
          Purchases themselves are handled by Apple; we never see your payment details.
        </li>
      </ul>

      <h2>Who else sees data</h2>
      <p>
        On the full plan, the words your trainer improvises are generated by Anthropic and
        voiced by ElevenLabs. They receive the run context needed for the line (your first
        name, the numbers of the run, the weather, and any stats you entered), and nothing
        that identifies your account. Weather comes from Open-Meteo and place names from
        BigDataCloud, both keyed on your location at the time. Subscriptions are managed
        through RevenueCat, which holds an anonymous id for your account and your Apple
        purchase record. Data is stored on Vercel.
      </p>

      <h2>What we do not do</h2>
      <p>
        No advertising, no selling of data, no tracking across other apps or sites. Location
        is used only while a run is being tracked.
      </p>

      <h2>Deleting your data</h2>
      <p>
        You can remove individual runs from the app at any time. To delete your account and
        everything stored with it, use Delete account on the Account screen, or contact
        [your contact email]. Deletion is permanent.
      </p>

      <h2>Contact</h2>
      <p>Questions about this policy: [your contact email].</p>
    </main>
  );
}
