import type { PersonaId } from "./types";

// Long continuous reads for the ElevenLabs Professional Voice Clone. The
// phrase bank alone is ~40 minutes of ideal in-character material; these
// passages push the total towards the 2-hour production-grade mark. Each is
// 60–90 seconds read aloud, written to be delivered IN CHARACTER at the same
// energy as the phrases — the clone reproduces the average delivery of its
// training data, so every second must sound like the trainer, not the actor's
// neutral voice. Content is phonetically varied on purpose: numbers, times,
// place names, questions, shouts, code-switching, the odd quieter beat.

export interface StudioRead {
  id: string;
  title: string;
  text: string;
}

const AHBENG_READS: StudioRead[] = [
  { id: "read-1", title: "Morning at East Coast", text: "Oi, listen ah, I tell you something about running in Singapore. Five thirty in the morning, kanina, East Coast Park already got more uncles than the kopitiam. Uncle in singlet, auntie with umbrella, all overtaking you like you standing still. You know why or not? Because they wake up and GO lah! No scrolling phone, no checking the weather app fourteen times, chee bye. Weather app say rain? Rain lah! You made of sugar issit? Your shoe waterproof, your skin waterproof, your excuses also waterproof. Out the door by five twenty-five, warm up by five thirty, first kilometre done before the sun even bother to show up. That's how my generation trained, and that's how you're going to train. Now stop listening and start moving!" },
  { id: "read-2", title: "The 2.4 story", text: "You want to hear about my two point four ah? Okay, sit down, kanina — no wait, don't sit down, keep jogging on the spot while I talk. Nineteen years old, Bedok camp, encik shouting until his voice crack. Eight rounds of the track, morning sun like a angry wok. First round easy lah, everybody hero. Third round, the chao keng ones start walking. Fifth round, got people seeing their breakfast again. But lim peh? Lim peh locked in, chee bye. Nine minutes forty-two seconds. The encik check his stopwatch twice, you know. TWICE! He say, boy, you run like the toilet on fire. I say encik, no, I run like the COOKHOUSE on fire, because that one got food inside. Discipline. That's the whole secret. Now show me yours!" },
  { id: "read-3", title: "Rain run", text: "Eh, so it's raining. And? You think Kelvin Kiptum stop training when got drizzle? You think the aunties at the wet market close shop because the sky leaking a bit, kanina? Rain is free air conditioning lah! Best running weather in Singapore, I tell you. Thirty-one degrees become twenty-six, the path all empty, no slow walkers blocking, no e-scooter hooligans. Just you, the rain, and the road. Chee bye, some of my best runs happen in the rain. Twelve kilometres in a thunderstorm once — okay lah, that one maybe not so smart, don't do that one. But light rain? Puddle here and there? That's not weather, that's SEASONING. Lace up, cap on, and chiong. The shower after will feel like heaven, I guarantee you." },
  { id: "read-4", title: "Char kway teow economics", text: "Let me teach you food mathematics, kanina. One plate char kway teow, the good one at the corner stall with extra hum — that's about seven hundred and forty calories. One hour of running at your speed — also about seven hundred calories, give or take your lan jiao pace. You see the problem or not? One hour of suffering equals ONE plate. Not two plates. Not one plate plus teh peng plus you know you want the goreng pisang also. ONE. So next time you order, I want you to hear my voice, chee bye. I want you to look at that plate and see sixty minutes of East Coast pavement staring back at you. Then eat it anyway lah, life is short — but TOMORROW, five thirty, you and me, we settle the bill. Interest included!" },
  { id: "read-5", title: "Marathon kings", text: "Fun fact time, and this one is true, okay, not kopitiam talk. The marathon is forty-two point one nine five kilometres because in nineteen oh eight, London Olympics, the royal family want the race to start at Windsor Castle and finish in front of their box at the stadium. Kings ah, sibei spoilt, kanina. Whole world run extra one point six kilometres for over a hundred years because some ang moh king cannot walk to the finish line himself. And you! You complain when I add two hundred metres to your route because got roadworks, chee bye. You know what that make you? Royalty complaint department. Next time you grumble, I remind you: somewhere out there, someone is running a full marathon for a king who never even said thank you. GO!" },
  { id: "read-6", title: "The void deck cat", text: "You know the orange cat at block four seven three? The one always sleeping by the letterbox like he pay rent there, kanina. That cat taught me more about running than any book. You know why? Because when that cat decide to move — WHEN he decide, chee bye — you never see anything so fast in your life. Zero to disappeared in one second. No warm-up drama, no checking his cat watch, no telling the other cats he going for a run first. Decide, then GO. That's it. That's the whole lesson. You? You spend twenty minutes choosing playlist, five minutes adjusting your sock, another ten minutes doing stretches you saw on the internet. The cat is laughing at you, kanina. Be like the cat. Decide. Then GO!" },
  { id: "read-7", title: "Hill repeats sermon", text: "Today I want to talk about hills, chee bye. Everybody hate hills. You see the slope at Mount Faber and your legs already writing resignation letter, kanina. But listen to me carefully: the hill is not your enemy. The hill is the only honest thing left in this world. Flat road can lie to you — wind behind you, feeling shiok, you think you improve. The hill? The hill tells the truth every single time. Heavier than last month? Hill knows. Skipped training two weeks? Hill knows, and the hill will TELL you, loudly, in your thighs. So we do repeats. Up, jog down, up again. Six times. You will hate me at number three, curse my ancestors at number five, and thank me at your next race. That's the deal. Uphill, GO!" },
  { id: "read-8", title: "Kopitiam critics", text: "Every Sunday morning after my long run, I sit at the kopitiam, kopi o kosong, and the uncles all got opinion, kanina. Uncle Lim say running spoil your knee. Uncle Lim also cannot climb one flight of stairs without sounding like a broken kettle, chee bye. Uncle Heng say last time he also run marathon — every year the story the timing get faster, ah, last week already two hours thirty. Miracle uncle! And Auntie Rose say why you torture yourself, come eat kaya toast. Auntie Rose I love you but no. You know what I tell them? I say uncle, auntie, when you eighty and still can carry your own groceries up the stairs, then we talk. Until then, lim peh going for round two. Some conversations you win with your legs, not your mouth!" },
  { id: "read-9", title: "Race morning briefing", text: "Okay listen up, race day briefing, no talking at the back, kanina. Number one: nothing new on race day. New shoes? No. New breakfast? No. That chia seed thing your colleague recommend yesterday? Absolutely not, chee bye, unless you want adventure at kilometre seven, and not the good kind. Number two: start slow. I know the gun go off and everybody sprint like got free bubble tea at the front. Let them go lah! You will collect them all back at kilometre fifteen, one by one, like paying respects. Number three: the wall is real but the wall is also a liar. When everything says stop, you still got twenty percent in the tank. Always got twenty percent. Number four, most important: enjoy it lah. You trained for this. The hay is in the barn. Now go and CHIONG!" },
  { id: "read-10", title: "Recovery day lecture", text: "Today is recovery day, and I know what you thinking, kanina. You thinking, coach, recovery day means I do nothing, right? Wrong, chee bye! Recovery is training. Say it with me: recovery IS training. Your muscles don't get stronger while you run — they get stronger while you sleep, while you eat properly, while you walk slowly to the kopitiam and DON'T order the fried carrot cake. Sleep eight hours, not scroll-phone-until-two-am and call it seven. Drink water until your pee look like nothing happened. Stretch the calves, roll the thigh, ten minutes, while watching your drama also can. The runners who break are not the lazy ones — they're the ones who never rest, kanina. Even lim peh rest. Even the MRT rest at night. Rest like a professional. Tomorrow we fly!" },
  { id: "read-11", title: "Numbers don't lie", text: "Let's talk numbers, because numbers don't bluff, kanina. Last month your five kilometre was thirty-two minutes fifteen. Yesterday? Thirty minutes forty. That's one minute thirty-five seconds faster, chee bye — that's nineteen seconds per kilometre. You know how big that is? That's overtaking a whole bus stop of people at the park connector. Your resting heart rate: was seventy-four, now sixty-eight. Your longest run: was six kilometres and complaining, now eleven kilometres and only MOSTLY complaining. This is compound interest, lim peh style. Nobody saw you improve on any single day — but stack ninety days of small boring efforts and suddenly, wah, who is this runner? So when you feel like nothing is happening, look at the numbers. The numbers remember everything you forget. Now go make next month's numbers jealous!" },
  { id: "read-12", title: "The MRT sprint", text: "True story, kanina. Last Tuesday, Tanjong Pagar station, I see a man in office clothes make the greatest athletic performance of the year, chee bye. Doors closing, he's at the top of the escalator with a briefcase and teh in a plastic bag. Most people give up, right? Wait four minutes for the next train, no shame. Not this hero. This uncle CHIONG. Full sprint, tie flying over the shoulder, briefcase tucked like rugby, and the teh — the teh never spilled ONE DROP, kanina! He slide through the door sideways like action movie. Whole platform want to clap. You know what this tells me? Everybody got a sprint inside them. EVERYBODY. You just need a good enough reason. So today, when I say pick up the pace, you imagine those doors closing. GO!" },
  { id: "read-13", title: "Why I coach", text: "People ask me, eh, why you shout at strangers for a living, kanina? Sit down, I tell you — no, keep stretching while I talk. When I was young and useless, somebody shouted at me. My encik. Every morning, rain or shine, this man treated my excuses like mosquitoes — SLAP, gone, next one, SLAP. I hated him for two years, chee bye. Two years! Then one day I ran nine forty-two for the two point four, and at the finish this fierce man got something in his eye, and I understood everything. He never shout because he angry at me. He shout because he saw where I could go, and my own excuses were driving the bus the wrong way, kanina. So now it's my turn. When I scold you, that's me seeing your finish line before you do. Don't thank me. RUN!" },
  { id: "read-14", title: "Heat management", text: "Singapore heat is not a joke, so listen properly, this part I'm not even going to insult you, kanina. Thirty-two degrees with humidity is a different sport. Rule one: run early or run late. Midday running is for mad dogs and tourists, chee bye. Rule two: water before you're thirsty. By the time your mouth complains, you're already one litre behind schedule. Small sips, every fifteen minutes, not one giant gulp at the end like a camel. Rule three: slow down and don't be proud. Same effort in the heat is thirty seconds per kilometre slower, and that's PHYSICS, not weakness. Rule four: light colour shirt, cap, and sunscreen — yes, sunscreen, you think skin cancer scared of your lan jiao tan line? And if you feel dizzy, got goosebumps in the heat, you STOP. That one is non-negotiable. Heat we respect. Everything else, we CHIONG!" },
  { id: "read-15", title: "The last four hundred", text: "This one I want you to memorise, because one day you will need it, kanina. Every race, every hard run, there is a moment near the end — maybe four hundred metres out — where your whole body files a complaint, chee bye. Legs say cannot. Lungs say crazy issit. Brain start negotiating: eh, walking also is moving what. That moment? That moment is the entire reason we train. Not for the medal, not for the run card, not even for the char kway teow after. For THAT moment — because how you answer it becomes who you are, and not just in running, I tell you. So here's what you do. Shorten your stride. Lift your eyes. Pick one thing far away — lamppost, tree, that auntie with the trolley — and take it. Then pick the next one. Four hundred metres is just eight lampposts, kanina. EIGHT. Now GO and take them all!" },
];

// A solid general-purpose set for other personas — still written to be
// performed fully in character, whoever's chair the actor is sitting in.
const GENERIC_READS: StudioRead[] = [
  { id: "read-1", title: "Why mornings win", text: "Let me tell you about morning runs. The city before seven belongs to a secret club, and the membership fee is just getting out of bed. The air is cooler by five degrees, the paths are empty, and your phone hasn't started shouting yet. Everything you do before breakfast is a gift to the rest of your day. That meeting at eleven? Easier, because you already did a hard thing today. The queue at lunch? Doesn't touch you — you watched the sunrise from kilometre four. People think morning runners have discipline. Wrong. We have a secret: the first five minutes are terrible for everyone, champion. Everyone! The only difference is we've learned the next twenty-five are worth it. Set the alarm. Lay out the shoes tonight. I'll handle the rest." },
  { id: "read-2", title: "The long run", text: "Sunday long runs are where runners are actually made. Not the intervals, not the races — the long, unglamorous kilometres where nothing happens except everything. Here's how to do them right. Start slower than feels respectable; if you can't hold a conversation, you're racing, not building. Bring water for anything past an hour. Pick a route with an escape hatch — a bus route home, in case today isn't your day, because some days aren't, and that's fine. Around kilometre nine or ten, something interesting happens: the chatter in your head runs out of material, and it gets quiet in there. That quiet is the good stuff. Problems untangle themselves. By the time you're home, stretching on the void deck, you're a slightly different person than the one who left. That's the whole product." },
  { id: "read-3", title: "Numbers and patience", text: "Here's the mathematics of getting better, and I need you to actually believe it. Improvement is boring. It's two percent here, nineteen seconds there, one extra kilometre on a Tuesday nobody will remember. Your five K time doesn't drop because of one heroic session — it drops because of forty unheroic ones. Look at your own numbers from three months ago: the pace that used to be a sprint is now your comfortable cruise. Nobody saw it happen, including you. That's compound interest, and your legs are the bank. So when a week feels wasted, when the run felt heavy and slow, write it down anyway. Deposits count even when they're small. The withdrawal comes on race day, all at once, and it will feel like magic. It isn't. It's Tuesdays." },
  { id: "read-4", title: "Rainy day case", text: "It's raining, and you're standing at the window doing negotiations. Let me settle this. Rain is the most underrated running weather there is. The temperature drops, the crowds vanish, and there's a rhythm to rain on a cap that no playlist can match. Your shoes will dry. Your clothes will wash. Your skin — this is important — is fully waterproof, and has been your entire life. The first two minutes are the only bad part, that cold shock when you step out. After that, you're just a person moving through weather, which is what runners have been since the beginning. Some of your best runs are waiting inside days like this, the ones nobody else wanted. Take the cap, skip the phone armband, go collect an empty path. The hot shower afterward is the best one all week. I promise." },
  { id: "read-5", title: "Race morning", text: "Race morning rules, so listen carefully, because adrenaline makes people creative in all the wrong ways. Nothing new today. Not the shoes, not the breakfast, not the gel a stranger handed you at the expo. Eat what you always eat, three hours out. Arrive early enough to queue for the toilet twice — you'll want to, trust me. When the gun goes, everyone around you will sprint like the finish line is at two hundred metres. Let them go. You'll see them again at fifteen kilometres, and you'll pass them so gently they won't even be angry. Run the first third with your head, the second third with your training, and the last third with whatever's left in your chest. And in the final stretch, look up — not at your watch. You'll want to remember it, not the number." },
  { id: "read-6", title: "The comeback", text: "So you stopped for a while. Three weeks, three months, doesn't matter — the couch got comfortable, life got loud, and the shoes went quiet in the corner. Here's what I need you to know: nobody is keeping score except you, and the road holds no grudges. The first run back will be humbling. Your lungs will file complaints, your pace will look like a typo, and some part of you will whisper that you've lost it all. You haven't. Fitness fades slower than the fear says, and it returns faster than you expect — the body remembers the route even when the calendar forgot. So we start stupidly small. Twenty minutes, easy, no watch if the watch makes you sad. Then again in two days. The comeback isn't one dramatic run. It's the second one, and the boring third. Welcome back. I kept your spot." },
  { id: "read-7", title: "Hills", text: "Let's talk about the hill, since you keep routing around it. The hill is honest. Flat roads flatter you — a tailwind here, fresh legs there, and you think you've improved. The hill has no opinion and tells no lies. It weighs exactly what you weigh, and it answers only to the work you've actually done. That's why we're going to make friends with it. Shorten your stride going up, like climbing stairs. Arms drive, eyes ten metres ahead, not at the top — the top is a rumor until you're on it. And here's the secret nobody tells beginners: the way down is a gift, free speed, if you lean forward slightly and let it carry you instead of braking the whole way. Six repeats today. You'll curse me at four. At your next race, on that bridge at kilometre eleven, you'll understand." },
  { id: "read-8", title: "Fuel", text: "Food is training, so let's get the fuel story straight. You cannot out-run a chaotic kitchen, but you also don't need to eat like a monk — runners who forbid everything end up face down in a birthday cake by Friday. The boring basics win: real breakfast, protein after hard sessions, water all day and not just a panic litre before bed. The night before a long run, carbs are your friend — rice, noodles, bread, whatever your grandmother would recognize as dinner. Nothing brand new before a race, ever; your stomach hates surprises more than any other organ you own. And after the long ones, eat properly and without guilt — that meal is part of the workout, the part where the fitness actually gets installed. Earn it, enjoy it, and be ready to earn the next one." },
  { id: "read-9", title: "Bad runs", text: "Today's run was terrible, and I want to talk about it, because nobody warns you about the random bad day. You slept fine. You ate fine. Same route, same shoes, same everything — and your legs ran like they were borrowed from a much more tired person. Here's the truth: bad runs are not messages. They're weather. They arrive uninvited, mean nothing, and leave the same way. The fittest athletes on the planet get them — ask anyone honest. The mistake is reading them like tea leaves: I've lost it, the plan's not working, maybe I'm not a runner. Nonsense. You finished a run that felt like wading through porridge — that's the most valuable session of the month, because the easy days teach your legs and the ugly days teach your head. Log it, shower, eat something good. Tomorrow's forecast is better." },
  { id: "read-10", title: "The five-minute rule", text: "Here is the only motivation trick I've ever needed, and I'm giving it to you free. It's called the five-minute rule. You don't have to run today — you only have to run for five minutes. That's the entire contract. Shoes on, out the door, five minutes of shuffling, and if at the end of it you genuinely want to stop, you stop, come home, no guilt, full credit. Sounds like a scam, doesn't it? Here's the data from every runner who's ever tried it: about nine times out of ten, minute five arrives and you just... keep going. Because starting was the whole battle. The body was never the problem — the doorway was. The other one time out of ten? You stop, and it's usually right to, because something real was wrong. The rule filters excuses from signals. Five minutes. That's all I'm asking. Deal?" },
  { id: "read-11", title: "Watching the greats", text: "Sit down, I want to tell you what the fastest marathoners on Earth actually look like, because it isn't what people think. Two hours and about thirty-five seconds — that's the men's record pace, roughly two minutes and fifty-one seconds per kilometre, held for forty-two of them in a row. Most people can't hold that pace to the end of the street. But here's the beautiful part: watch their faces. No drama. No gritted teeth until the very end. Just relaxed shoulders, quick light steps, like the whole thing was arranged with the road in advance. That relaxation is the masterpiece — it took ten thousand unglamorous mornings to look that casual. You and I aren't chasing their clock. We're stealing their secret: hard and frantic are different things. Fast is smooth. Smooth is learnable. Class dismissed — now run your own race." },
  { id: "read-12", title: "The finish line speech", text: "One day soon you're going to finish something you once thought was impossible — a distance, a time, a race with your name printed on the bib. And I want you to know now, in advance, what that last hundred metres will hold, so you don't miss it while it's happening. Your legs will be gone. Properly gone. The crowd noise will sound like it's underwater, and the clock will be doing its countdown. And a version of you — the one from months ago, the one who couldn't run to the corner, who signed up half as a joke — will be standing just past the line, waiting to be replaced. Cross it for them. Raise your arms; you will not look silly, everyone does it, it's tradition. And when someone hangs the medal on you, let it be heavy. You didn't get lucky. You built this. Every kilometre — every single one — counted." },
];

export function readsFor(persona: PersonaId): StudioRead[] {
  return persona === "ahbeng" ? AHBENG_READS : GENERIC_READS;
}

// ---- test sessions: a <5 minute dry run of the whole pipeline ----

export const TEST_PHRASES: { id: string; text: string }[] = [
  { id: "test-1", text: "Welcome to the test session — this is phrase number one." },
  { id: "test-2", text: "The quick brown fox jumps over the lazy dog." },
  { id: "test-3", text: "Three kilometres down, and the weather is looking great today." },
  { id: "test-4", text: "Pick up the pace — you have far more in the tank than you think!" },
  { id: "test-5", text: "Halfway there. Breathe easy, relax the shoulders, and cruise." },
  { id: "test-6", text: "That was your fastest split of the morning. Outstanding work." },
  { id: "test-7", text: "Water break at the next corner, then we go again." },
  { id: "test-8", text: "One hundred metres to go — empty everything you have left!" },
  { id: "test-9", text: "And that's the finish line. What a run that was." },
  { id: "test-10", text: "Session complete. Same time tomorrow — rest well tonight." },
];

export const TEST_READS: StudioRead[] = [
  { id: "read-1", title: "Test paragraph one", text: "This is the first test paragraph, read at a natural, relaxed pace. The purpose of this recording is to check the full pipeline from the browser to storage and onward to the voice platform. Numbers help too: one, two, three, four, five, sixty-seven, and nineteen ninety-nine. A question sounds different from a statement, doesn't it? And an exclamation carries real energy! That should be plenty for this one." },
  { id: "read-2", title: "Test paragraph two", text: "Here is a second, slightly different passage. Morning runs along the water are quieter than evening ones; the air is cooler, the paths are emptier, and the city hasn't started shouting yet. Speak this one with a little more warmth and energy than the first, as if encouraging a friend through the final kilometre of a long, hard run they almost skipped." },
  { id: "read-3", title: "Test paragraph three", text: "The third and final passage checks pace changes. Start slowly, deliberately, one word at a time. Then lift the tempo through the middle of the paragraph until it moves briskly, confidently, with momentum. And finally, ease back down for the ending — slow, calm, and settled, like a runner crossing the line and catching their breath at last." },
];
